### PR TITLE
Added 'atoms.png' minimalistic wallpaper

### PR DESCRIPTION
**Pull request by shvedes**

### CODE REVIEW

**Comment by shvedes** [comment]
well i guess it's too much...

**Comment by shvedes** [comment]
Thank you

**Comment by AngelJumbo** [comment]
@shvedes I'm sorry for the wait. I've been bussy and I didn't notice the notifications. I never reject anything in this repo, you can add as many images as you want. :')

**Comment by shvedes** [comment]
It's ok, I'm not pretending to fast merge, I'm just doing what I like :) 
Also, thank you for approving my images!
Will do more later!

**Pull request merged**
