### PR TITLE
Today is November, 29th and this is your daily dose of gruvbox

### PR DESCRIPTION
**Pull request by shvedes**
I'm crazy, ngl

### CODE REVIEW

**Comment by AngelJumbo** [comment]
I might need to make some changes y in the folder structure after this one, It would be an interesting task for another day.

**Comment by shvedes** [comment]
Should I stop PR'ing until that?

**Comment by AngelJumbo** [comment]
na, its fine, I will not change anything until a week or so.

**Comment by AngelJumbo** [comment]
I will merge the light section with in the other ones , every section will have a light subsection. I have to change the scripts.

**Comment by shvedes** [comment]
Got it. Thanks for the info

**Pull request merged**
